# Social Indicators

## Data preparation

In [3]:
import pandas as pd

In [97]:
def get_data_worldbank_xls(path):

    df = pd.read_excel(
        pd.ExcelFile(path),
        sheet_name='Data',
        skiprows=3
    )

    df.drop(columns=["Country Name", "Indicator Name", "Indicator Code", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2025"], inplace=True)

    df.dropna(
        thresh=len(df.columns) // 2,
        inplace=True
    )

    return df

In [99]:
df_ed_gov_exp = get_data_worldbank_xls('data/education_gov_expenditure_%.xls')

df_ed_post_sec = get_data_worldbank_xls('data/education_post_secondary_%.xls')

df_ec_gni_pc = get_data_worldbank_xls('data/economic_gni_per_capita.xls')

df_ec_gini_idx = get_data_worldbank_xls('data/economic_gini_index.xls')

df_urban_pop = get_data_worldbank_xls('data/urban_population_%.xls')

In [101]:
df_female_labor_ratio = pd.read_csv('data/female_to_male_labor_force_ratio_%.csv')

df_female_labor_ratio.drop(columns=["Country Name", "Indicator Name", "Indicator Code", "Disaggregation"], inplace=True)

In [102]:
df_female_parliament_sits = pd.read_csv('data/female_parliament_seats_%.csv')

df_female_parliament_sits.drop(columns=["Country Name", "Indicator Name", "Indicator Code", "Disaggregation"], inplace=True)

In [106]:
df_life_expect = pd.read_csv('data/life_expectancy.csv')
df_life_expect.drop(columns=["Entity"], inplace=True)

df_life_expect

      Code  Year  Life expectancy
0      AFG  1950          28.1563
1      AFG  1951          28.5836
2      AFG  1952          29.0138
3      AFG  1953          29.4521
4      AFG  1954          29.6975
...    ...   ...              ...
21560  ZWE  2019          61.0603
21561  ZWE  2020          61.5300
21562  ZWE  2021          60.1347
21563  ZWE  2022          62.3601
21564  ZWE  2023          62.7748

[21565 rows x 3 columns]

In [109]:
df_rule_of_law = pd.read_excel(
    pd.ExcelFile('data/rule_of_law_index.xlsx'),
    sheet_name="Historical Data"
)

df_rule_of_law

,Country,Year,Country_year,Country Code,Region,WJP Rule of Law Index: Overall Score,Factor 1: Constraints on Government Powers,1.1 Government powers are effectively limited by the legislature,1.2 Government powers are effectively limited by the judiciary,1.3 Government powers are effectively limited by independent auditing and review,...,7.6. Civil justice is effectively enforced,"7.7 Alternative dispute resolution mechanisms are accessible, impartial, and effective",Factor 8: Criminal Justice,8.1 Criminal investigation system is effective,8.2 Criminal adjudication system is timely and effective,8.3 Correctional system is effective in reducing criminal behavior,8.4 Criminal system is impartial,8.5 Criminal system is free of corruption,8.6 Criminal system is free of improper government influence,8.7. Due process of the law and rights of the accused
0,Albania,2012-2013,Albania_2012-2013,ALB,Eastern Europe and Central Asia,0.489781,0.457571,0.570000,0.340000,0.370000,...,0.580000,0.690000,0.410052,0.330000,0.420000,0.390000,0.490000,0.320000,0.410000,0.510000
1,Argentina,2012-2013,Argentina_2012-2013,ARG,Latin America and Caribbean,0.505377,0.459925,0.500000,0.390000,0.440000,...,0.340000,0.700000,0.434365,0.300000,0.320000,0.320000,0.590000,0.470000,0.460000,0.580000
2,Australia,2012-2013,Australia_2012-2013,AUS,East Asia and Pacific,0.825011,0.883457,0.910000,0.880000,0.850000,...,0.770000,0.850000,0.723643,0.560000,0.620000,0.650000,0.600000,0.890000,0.940000,0.810000
3,Austria,2012-2013,Austria_2012-2013,AUT,"EU, EFTA, and North America",0.805552,0.822501,0.880000,0.800000,0.700000,...,0.790000,0.940000,0.747908,0.640000,0.750000,0.700000,0.640000,0.860000,0.850000,0.800000
4,Bangladesh,2012-2013,Bangladesh_2012-2013,BGD,South Asia,0.395318,0.402931,0.520000,0.410000,0.390000,...,0.270000,0.400000,0.381836,0.470000,0.420000,0.290000,0.450000,0.320000,0.400000,0.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1479,Uzbekistan,2025,Uzbekistan_2025,UZB,Eastern Europe and Central Asia,0.496876,0.373136,0.326245,0.371554,0.300253,...,0.486457,0.590007,0.457834,0.504760,0.624717,0.643310,0.354093,0.456083,0.220476,0.401398
1480,"Venezuela, RB",2025,"Venezuela, RB_2025",VEN,Latin America and Caribbean,0.259741,0.178045,0.333402,0.126796,0.079583,...,0.179356,0.411658,0.106996,0.086139,0.113122,0.067291,0.098055,0.234633,0.008474,0.141255
1481,Vietnam,2025,Vietnam_2025,VNM,East Asia and Pacific,0.495496,0.454408,0.387021,0.362390,0.491494,...,0.425840,0.568591,0.480391,0.538223,0.558934,0.466553,0.505527,0.534028,0.278228,0.481244
1482,Zambia,2025,Zambia_2025,ZMB,Sub-Saharan Africa,0.449919,0.462974,0.493487,0.380695,0.492761,...,0.572310,0.551743,0.406804,0.460349,0.470246,0.312702,0.468699,0.342157,0.418819,0.374655
1483,Zimbabwe,2025,Zimbabwe_2025,ZWE,Sub-Saharan Africa,0.392772,0.318180,0.324443,0.303297,0.422715,...,0.605623,0.541715,0.351063,0.422368,0.446302,0.353399,0.366535,0.327120,0.190770,0.350950